version: '3'

services:
  database:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  php-apache:
    build:
      context: ../
      dockerfile: docker/php-apache/Dockerfile
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=10.5
      - MAILER_DSN=${MAILER_DSN}
      - MAILER_EMAIL=${MAILER_EMAIL}
    volumes:
      - ./logs:/var/log
    ports:
      - "80:80"
